"""new fields in user model

Revision ID: 96117ee93680
Revises: 2fcbbe392f4c
Create Date: 2021-02-19 09:44:36.540422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96117ee93680'
down_revision = '2fcbbe392f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
